# Generated by Django 6.0.2 on 2026-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alumnogrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('TUTOR', 'Tutor'), ('OPERADOR', 'Operador'), ('ALUMNO', 'Alumno')], default='ALUMNO', max_length=20),
        ),
    ]
