# Generated by Django 6.0.2 on 2026-03-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnogrupo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE_INGRESO", "Pendiente de ingreso"),
                    ("ACTIVO", "Activo"),
                    ("PENDIENTE_SALIDA", "Pendiente de salida"),
                ],
                default="PENDIENTE_INGRESO",
                max_length=30,
            ),
        ),
    ]

