# Generated by Django 6.0.2 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alumnogrupo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='abreviatura',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
