# Generated by Django 6.0.2 on 2026-03-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_carrera_abreviatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
