# Generated by Django 6.0.2 on 2026-03-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoperfil',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
