# Generated by Django 6.0.2 on 2026-03-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_conexionusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnoperfil',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='alumnoperfil',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='alumnoperfil',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='alumnoperfil',
            name='twitter',
        ),
        migrations.AddField(
            model_name='user',
            name='biografia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
