# Generated by Django 6.0.2 on 2026-03-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_alumnoperfil_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('piezas_requeridas', models.IntegerField()),
                ('color', models.CharField(default='#2D6A4F', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuración de Nivel',
                'verbose_name_plural': 'Configuraciones de Niveles',
                'ordering': ['nivel'],
            },
        ),
    ]
