# Generated by Django 6.0.2 on 2026-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_nivelconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnoperfil',
            name='max_racha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='racha_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnoperfil',
            name='ultima_fecha_racha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
