# Generated by Django 6.0.2 on 2026-02-14 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0001_initial'),
        ('users', '0002_carrera_alumnoperfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.OneToOneField(limit_choices_to={'role': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reciclaje.grupo')),
            ],
        ),
    ]
