# Generated by Django 6.0.2 on 2026-03-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0003_metasistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='codigo_invitacion',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
