# Generated by Django 6.0.2 on 2026-03-22 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0005_metaalumno'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono_lucide', models.CharField(default='Award', help_text='Nombre del icono de Lucide (ej: Award, Star, Crown)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedallaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_obtenida', models.CharField(help_text='Formato YYYY-MM o Nombre del Mes', max_length=20)),
                ('fecha_otorgada', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(limit_choices_to={'role': 'ALUMNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='medallas', to=settings.AUTH_USER_MODEL)),
                ('medalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciclaje.medalla')),
            ],
        ),
    ]
