# Generated by Django 6.0.2 on 2026-03-22 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0006_medalla_medallaalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='metasistema',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metas_sistema', to='reciclaje.material'),
        ),
    ]
