# Generated by Django 6.0.2 on 2026-03-23 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0007_metasistema_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposito',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
