# Generated by Django 6.0.2 on 2026-03-23 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0008_alter_deposito_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaalumno',
            name='cumplida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metaalumno',
            name='fecha_cumplimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metasistema',
            name='cumplida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metasistema',
            name='fecha_cumplimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metasistema',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
