# Generated by Django 6.0.2 on 2026-03-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0009_metaalumno_cumplida_metaalumno_fecha_cumplimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medalla',
            name='mes',
            field=models.IntegerField(blank=True, help_text='1=Ene, 2=Feb, etc. (Para temáticas mensuales)', null=True),
        ),
        migrations.AddField(
            model_name='medalla',
            name='posicion',
            field=models.IntegerField(blank=True, help_text='1, 2, o 3 para medallas de ranking', null=True),
        ),
        migrations.AddField(
            model_name='medalla',
            name='tipo',
            field=models.CharField(choices=[('RANKING', 'Ranking Mensual'), ('META', 'Meta/Objetivo')], default='RANKING', max_length=20),
        ),
        migrations.AddField(
            model_name='medallaalumno',
            name='categoria',
            field=models.CharField(blank=True, help_text="Ej: 'Global', 'Botellas', 'Quizzes'", max_length=100),
        ),
        migrations.CreateModel(
            name='AsignacionMedallaMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('año', 'mes')},
            },
        ),
    ]
