# Generated by Django 6.0.2 on 2026-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclaje', '0002_material_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_meta', models.PositiveIntegerField()),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
